### ISSUE TITLE
Failing to build in nodejs 0.10.21

### ISSUE THREAD

**Issue by pmccarren** [jiangmiao/node-curl#23]
Hello! When I try to install this package, npm fails.

I'm currently using node v0.10.21, and npm verson 1.3.6.
Thanks,
Patrick

**Comment by jiangmiao** [comment]
What's the error output. I compile on v0.10.21 succeesfully on my computer.

**Comment by pmccarren** [comment]
Same error when running as local user, and root.

Here's the error output:

``` text
 ~ $ npm install node-curl
npm http GET https://registry.npmjs.org/node-curl
npm http 304 https://registry.npmjs.org/node-curl

> node-curl@0.3.1 install /home/pmccarren/node_modules/node-curl
> sh src/generate_curl_options_list.sh && (node-gyp rebuild || node-waf configure build)

extract constants from 
generate src/integer_options.h
cat: : No such file or directory
generate src/string_options.h
cat: : No such file or directory
generate src/integer_infos.h
cat: : No such file or directory
generate src/string_infos.h
cat: : No such file or directory
generate src/double_infos.h
cat: : No such file or directory
make: Entering directory `/home/pmccarren/node_modules/node-curl/build'
  CXX(target) Release/obj.target/node-curl/src/node-curl.o
In file included from ../src/node-curl.cc:1:0:
../src/node-curl.h:7:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
                       ^
compilation terminated.
make: *** [Release/obj.target/node-curl/src/node-curl.o] Error 1
make: Leaving directory `/home/pmccarren/node_modules/node-curl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.11.4-201.fc19.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pmccarren/node_modules/node-curl
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
sh: node-waf: command not found
npm ERR! weird error 127                                                                                                                                                                            
npm ERR! not ok code 0 
```

**Comment by jiangmiao** [comment]
You need libcurl-dev installed in the system.

**Comment by pmccarren** [comment]
That did it. Thanks for clearing that up
